name: Pipe N1 Testes com Mocha

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: yarn install

      - name: Executar testes com Mocha
        run: yarn test

      - name: Publicar Relatório de Testes JUnit
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: relatorio-execucao-manual
          path: reports/junit.xml

      