name: Testes Manuais com Mocha

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: yarn install

      - name: Executar testes com Mocha
        run: yarn test